source "https://rubygems.org"
gem "jekyll"
gem "minimal-mistakes-jekyll"
gem "jekyll-remote-theme"
gem "jekyll-include-cache"
gem "jekyll-paginate"
gem "jekyll-sitemap"
gem "jekyll-gist"
gem "jekyll-feed"
gemspec